name: Deploy standalone plugins to WordPress.org

on:
  # TODO The pull_request will be removed once the workflow is tested.
  pull_request:
    branches:
      - trunk
      - 'release/**'
      - 'feature/**'
    paths:
      - '.github/workflows/deploy-standalone-plugins.yml'
    types:
      - opened
      - reopened
      - synchronize
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      slug:
        type: choice
        options:
        - audit-autoloaded-options
        - audit-enqueued-assets
        - dominant-color-images
        - fetchpriority
        - sqlite
        - webp-support
        - webp-uploads
        description: 'The slug of the plugin to deploy'

jobs:
  release:
    name: Prepare Deployment
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install npm dependencies
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: npm ci
      - name: Get plugin version
        id: get-version
        uses: actions/github-script@v6
        with:
          script: |
            if ( ${{ github.event_name != 'workflow_dispatch' }} ) {
              return "auto";
            }

            const fs = require( 'fs' );
            const path = require( 'path' );

            let setMenualPluginVersion = '';
            const pluginsFile = path.join( '.', 'plugins.json' );
            let pluginsFileContent = '';
            try {
              pluginsFileContent = fs.readFileSync( pluginsFile, 'utf-8' );
            } catch ( err ) {
              log(
                formats.error(
                  `Error reading the file "${ buildLoadFile }": "${ err }"`
                )
              );
            }

            if ( pluginsFileContent === '' ) {
              console.log( `Error reading the file "${ pluginsFile }"` );
              return false;
            }

            for ( const moduleDir in pluginsFileContent ) {
              const pluginVersion = pluginsFileContent[ moduleDir ]?.version;
              const pluginSlug = pluginsFileContent[ moduleDir ]?.slug;

              if ( ! pluginVersion || ! pluginSlug ) {
                console.log(
                    'The given module configuration is invalid, the module JSON object is missing the "version" and/or "slug" properties, or they are misspelled.'
                );
                process.exit( 1 );
              }
              //console.log(pluginSlug);
              if ( "${{ inputs.slug }}" == pluginSlug ) {
                console.log(pluginVersion);
                return pluginVersion;
                //console.log( "Yesss" );
                setMenualPluginVersion = pluginVersion;
              } else {
                //console.log( "NOOO" );
              }
            }
      - name: Set matrix
        id: set-matrix
        run: |
          echo ${{ steps.get-version.outputs.result }}

          if [[ ${{ steps.get-version.outputs.result }} == 'auto' ]]; then
            echo "Auto";
          else
            echo "Manual";
          fi
          
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            # Set the manual input values in JSON format for use in the matrix.
            echo "matrix={\"include\":[{\"slug\":\"${{ inputs.slug }}\",\"version\":\"${{ inputs.version }}\"}]}" >> $GITHUB_OUTPUT
          else
            # Load the JSON file and parse from "{name: {slug, version}, ...}" to "include: [{ name, slug, version }, ...]"
            # for use in the matrix.
            echo "matrix="$(jq -c '{include:[keys[] as $k | {name:$k,slug:.[$k].slug,version:.[$k].version }]}' plugins.json) >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy Plugin
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.release.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Building standalone plugins
        run: npm run build-plugins
      - name: Deploy Standalone Plugin - ${{ matrix.slug }}
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ matrix.slug }}
          VERSION: ${{ matrix.version }}
          BUILD_DIR: ./build/${{ matrix.slug }}
          ASSETS_DIR: ./build/${{ matrix.slug }}/.wordpress-org
