name: Deploy to WordPress.org

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/deploy.yml'
      - '**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - trunk
      - 'release/**'
      - 'feature/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/deploy.yml'
      - '**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

#jobs:
#  release:
#    name: New Release
#    runs-on: ubuntu-latest
#    steps:
#      - uses: styfle/cancel-workflow-action@0.9.1
#      - uses: actions/checkout@v3
#      - name: Setup Node.js (.nvmrc)
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: '.nvmrc'
#          cache: npm
#      - name: npm install
#        run: npm ci
#      - name: Building standalone plugins
#        id: build-plugins
#        run: npm run build-plugins
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.set-names.outputs.names }}
      slugs: ${{ steps.set-slugs.outputs.slugs }}
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - id: set-names
        run: echo "names=$(jq 'keys' /path/to/plugins.json)" >> $GITHUB_OUTPUT
      - id: set-slugs
        run: echo "slugs=$(jq '.[].slug' /path/to/plugins.json)" >> $GITHUB_OUTPUT
      - id: set-versions
        run: echo "versions=$(jq '.[].version' /path/to/plugins.json)" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ${{ fromJSON(needs.job1.outputs.names) }}
        slug: ${{ fromJSON(needs.job1.outputs.slugs) }}
        version: ${{ fromJSON(needs.job1.outputs.versions) }}
