name: Deploy to WordPress.org

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/deploy.yml'
      - '**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - trunk
      - 'release/**'
      - 'feature/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/deploy.yml'
      - '**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

#jobs:
#  release:
#    name: New Release
#    runs-on: ubuntu-latest
#    steps:
#      - uses: styfle/cancel-workflow-action@0.9.1
#      - uses: actions/checkout@v3
#      - name: Setup Node.js (.nvmrc)
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: '.nvmrc'
#          cache: npm
#      - name: npm install
#        run: npm ci
#      - name: Building standalone plugins
#        id: build-plugins
#        run: npm run build-plugins
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix="$(jq -c '[keys[] as $k | {name:$k,slug:.[$k].slug,version:.[$k].version }]' plugins.json) >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(toJSON(needs.job1.outputs.matrix)) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: npm ci
      - name: Deploy Standalone Dominant Color
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ matrix.slug }}
          VERSION: 1.0.0
          BUILD_DIR: ./build/${{ matrix.slug }}
