name: 'WordPress Plugin Checks'
on:
  push:
    branches:
    - trunk

  pull_request:
    branches:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        ignore-codes: |
          WordPress.WP.I18n.TextDomainMismatch
